name: example_go_router
description: A complex example demonstrating GoRouter integration with Modularity.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.9.0 <4.0.0'

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.0.0 # Using recent version
  modularity_flutter:
    path: ../../packages/flutter

  modularity_contracts: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0







