name: modularity_test_utils
description: Testing utilities for Modularity framework.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=3.9.0 <4.0.0'
  flutter: ">=3.0.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  modularity_flutter:
    path: ../flutter

