name: example_bloc
description: Example of using BLoC with Modularity framework.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.9.0 <4.0.0'

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.0
  modularity_flutter:
    path: ../../packages/flutter
  modularity_core:
    path: ../../packages/core
  modularity_contracts:
    path: ../../packages/contracts

dev_dependencies:
  flutter_test:
    sdk: flutter

