name: modularity_core
description: Core implementation of Modularity framework providing dependency injection container and module lifecycle management.
version: 0.1.0
repository: https://github.com/cherrypick-agency/modularity_dart/tree/main/packages/core
issue_tracker: https://github.com/cherrypick-agency/modularity_dart/issues
topics:
  - dependency-injection
  - di
  - modules
  - architecture

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  modularity_contracts: ^0.1.0
  meta: ^1.7.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
