name: modularity_flutter
description: Flutter integration for Modularity framework. Provides widgets and utilities for module-based Flutter apps.
version: 0.0.2
repository: https://github.com/cherrypick-agency/modularity_dart/tree/main/packages/flutter
issue_tracker: https://github.com/cherrypick-agency/modularity_dart/issues
topics:
  - dependency-injection
  - di
  - flutter
  - modules

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  modularity_contracts: ^0.0.2
  modularity_core: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^3.0.0
